name: Java CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            job: [ test, spotless ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build/Test with Maven
        if: matrix.job == 'test'
        run: ./mvnw -B -ntp verify
      - name: Run Spotless
        if: matrix.job == 'spotless'
        run: ./mvnw spotless:check
